### ISSUE TITLE
Unsubscribe errors

### ISSUE THREAD

**Issue by little-wow** [creativecommons/communications#37]
More than one person has noticed that this happens when you unsubscribe from our lists. It needs to be fixed ASAP. I tried to find the screens in Civi, but couldn't. Help!

https://creativecommons.freshdesk.com/helpdesk/tickets/43113

[Image removed by Rob.]

CC @rebeccalendl @robmyers @ericsteuer

**Comment by rheaplex** [comment]
Googling this reveals -

http://civicrm.stackexchange.com/a/4463

which implies we could change the unsubscribe links in the email template to opt-outs.

Unless this is a legal compliance matter it's not urgent. But I will discuss it with Matt.

**Comment by mattl** [comment]
Yeah, should be an opt-out link.

**Comment by rheaplex** [comment]
Cool, thank you @mattl .

@little-wow is that something you can update?

**Comment by little-wow** [comment]
Can we have just an opt-out and no unsubscribe link? If so, yes, I can update.

**Comment by rheaplex** [comment]
That sounds good! I'd check with Legal that we can phrase it like that (you never know...) or whether we should just have the "unsubscribe" link go to the opt-out. But otherwise, cool.

**Comment by little-wow** [comment]
Will having people opt out of all communications rather than just unsubscribe from our announcements list mess with other comms?

**Comment by mattl** [comment]
I believe when you opt-out, you're opting out of the group. If people unsubscribe, they're opting out of all groups.

**Comment by little-wow** [comment]
It's the opposite-- if you opt-out you're opting out of all comms, if you unsubscribe it's just that link.  It's the unsubscribe link that's causing the issue

**Comment by alkrieger** [comment]
I believe this should be fixed as of last week -

Try https://donate.creativecommons.org/civicrm/mailing/unsubscribe?reset=1&jid=2319&qid=3428448&h=25675007d9cf490e

I think this related to redmine ticket #27249

We thought it was a Civi Permissions issue, but that turned out not to be the case. We wound up editing the Unsubscribe template in Civi directly, since there's no way to ensure that users are going to see a nice, client-facing group name or description. The template should now match what users see when they select an opt-out from all mailings - which is to say, a more generic interface that doesn't list the specific group.

@little-wow would you test?

**Comment by little-wow** [comment]
seems to have been fixed last week, sorry I didn't update the ticket!
